/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2016-09-01 08:12:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"generator\" content=\"Xinglan Wang (bxmn4728@163.com) \">\r\n");
      out.write("<!--pageMeta-->\r\n");
      out.write("\r\n");
      out.write("<!-- Loading Bootstrap -->\r\n");
      out.write("<link href=\"bootstrap/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Loading Flat UI -->\r\n");
      out.write("<link href=\"css/flat-ui.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- load page css -->\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/style.complete.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/myStyle.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("\t\t\t  <script src=\"js/html5shiv.js\"></script>\r\n");
      out.write("\t\t\t  <script src=\"js/respond.min.js\"></script>\r\n");
      out.write("\t\t\t<![endif]-->\r\n");
      out.write("\r\n");
      out.write("<!--headerIncludes-->\r\n");
      out.write("\r\n");
      out.write("<title>火星在线项目管理网</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"page\" class=\"page\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"item header margin-top-0 padding-bottom-0\" id=\"header3\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<header class=\"wrapper image image1\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"bg bg1\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"row banner2\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-8 col-md-offset-2 text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/hexagon.png\" alt=\"logo\" />\r\n");
      out.write("\t\t\t\t\t\t\t<h1>火星在线项目管理</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"lead\">\r\n");
      out.write("\t\t\t\t\t\t\t\t使用火星在线项目管理网站，是一个在线的轻量级的项目管理软件，在线即可进行项目管理，使用便捷,轻松实现办公网络化、现代化。</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-default btn-lg btn-wide\">登陆</a>\r\n");
      out.write("\t\t\t\t\t\t\t <a href=\"#\" class=\"btn btn-primary btn-lg btn-wide\">注册</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /.container -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.wrapper -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- /.item -->\r\n");
      out.write("\t\t<!-- Start Content Block 2-2 -->\r\n");
      out.write("\t\t<section id=\"content-2-2\"\r\n");
      out.write("\t\t\tclass=\"content-block content-2-2 bg-pomegranate\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<!-- Start Row -->\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 col-xs-12 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"icon-outline\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<span><img alt=\"plane\" src=\"images/plane.png\"></span></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>简单、有序的项目协作管理</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>项目过程、清晰可见</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>项目进展、一目了然</P>\r\n");
      out.write("\t\t\t\t\t\t\t<p>项目资料、随时查阅</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 col-xs-12 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"icon-outline\">\r\n");
      out.write("\t\t\t\t\t\t\t<span><img alt=\"star\" src=\"images/star.png\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>高效、便捷的任务分配、管理和跟踪</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>快速分配、多人协作</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>汇报进展、讨论问题</P>\r\n");
      out.write("\t\t\t\t\t\t\t<p>多级查看、关注细节</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 col-xs-12 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"icon-outline\">\r\n");
      out.write("\t\t\t\t\t\t\t<span><img alt=\"tag\" src=\"images/tag.png\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>多种方式自动组织和管理</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p>各级组织、各归各处</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>资源分配、清晰明了</P>\r\n");
      out.write("\t\t\t\t\t\t\t<p>图像显示、直观明确</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--// END Row -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<!--// END Content Block 2-2 -->\r\n");
      out.write("\t\t<!-- Start Content Block 1-9 -->\r\n");
      out.write("\t\t<section id=\"content-1-9\" class=\"content-1-9 content-block\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"underlined-title\">\r\n");
      out.write("\t\t\t\t\t<div class=\"editContent\">\r\n");
      out.write("\t\t\t\t\t\t<h1>What we do!</h1>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t<div class=\"editContent\">\r\n");
      out.write("\t\t\t\t\t\t<h2>我们提供卓越的服务</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 col-sm-12 col-xs-12 \">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"fa fa-pencil\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>项目信息管理</h4>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>帮助您便捷的创建项目，管理项目基本信息。 </p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 col-sm-12 col-xs-12 \">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"fa fa-code\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>WBS分解</h4>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>便捷输入项目的分支节点，可以进行资源分配</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 col-sm-12 col-xs-12 \">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"fa fa-comments-o\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>甘特图展示</h4>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>基于WBS分解的任务，进行直观展示</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 col-sm-12 col-xs-12 \">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"#\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>基于任务的资源分配（人，财、物）</h4>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>根据任务的资源分配，实现资源的合理利用</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 col-sm-12 col-xs-12 \">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"fa fa-mobile\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>进度更新</h4>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>根据实际的完成时间，实时更新甘特图</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 col-sm-12 col-xs-12 \">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"fa fa-bookmark\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>关键路径</h4>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>在甘特图实现关键路径上各个任务的链接</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-3 col-sm-12 col-xs-12 \">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"fa fa-bookmark\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>资源管理</h4>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>能够查看资源、人员的库存，分配情况</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-3 col-sm-12 col-xs-12 \">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"fa fa-bookmark\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>其他功能</h4>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>我们将不断完善我们的功能</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /.row -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /.container -->\r\n");
      out.write("\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<!-- // End Content Block 1-9 -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- Start Content Block 2-7 -->\r\n");
      out.write("\t\t<section id=\"content-2-7\" class=\"content-block content-2-7\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"underlined-title\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h1>我们的成绩 </h1>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"counter-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t<span><img alt=\"magic\" src=\"images/magic.png\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"counter-text\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3 class=\"counter\">789名</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>使用者</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"counter-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t<span><img alt=\"idea\" src=\"images/idea.png\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"counter-text\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3 class=\"counter\">1049个</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>项目</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"counter-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t<span><img alt=\"time\" src=\"images/time.png\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"counter-text\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3 class=\"counter\">10345时</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"editContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>总在线时长</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /.container -->\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t <!--// END Content Block 2-7 -->\r\n");
      out.write("\t\t");
/*<div class="item portfolio" id="portfolio2">

			<div class="container">

				<div class="row margin-bottom-40">

					<div class="col-md-12">

						<p class="lead text-center editContent"></p>

					</div>
					<!-- /.col-md-12 -->

				</div>
				<!-- /.row -->

				<div class="row margin-bottom-20">

					<div class="col-md-3">

						<a href="" class="over"> <img src="images/portfolio1.jpg"
							class="img-rounded width-100" alt="" id="testImage">
							<p></p>
						</a>

					</div>
					<!-- /.col-md-3 col -->

					<div class="col-md-3">

						<a href="" class="over"> <img src="images/portfolio2.jpg"
							class="img-rounded width-100" alt="">
						</a>

					</div>
					<!-- /.col-md-3 col -->

					<div class="col-md-3">

						<a href="" class="over propClone"> <img
							src="images/portfolio3.jpg" class="img-rounded width-100" alt="">
						</a>

					</div>
					<!-- /.col-md-3 col -->

					<div class="col-md-3">

						<a href="" class="over"> <img src="images/portfolio4.jpg"
							class="img-rounded width-100" alt="">
						</a>

					</div>
					<!-- /.col-md-3 col -->

				</div>
				<!-- /.row -->

				<div class="row margin-bottom-20">

					<div class="col-md-3">

						<a href="" class="over"> <img src="images/portfolio5.jpg"
							class="img-rounded width-100" alt="">
						</a>

					</div>
					<!-- /.col-md-3 col -->

					<div class="col-md-3">

						<a href="" class="over"> <img src="images/portfolio6.jpg"
							class="img-rounded width-100" alt="">
						</a>

					</div>
					<!-- /.col-md-3 col -->

					<div class="col-md-3">

						<a href="" class="over"> <img src="images/portfolio7.jpg"
							class="img-rounded width-100" alt="">
						</a>

					</div>
					<!-- /.col-md-3 col -->

					<div class="col-md-3">

						<a href="" class="over"> <img src="images/portfolio8.jpg"
							class="img-rounded width-100" alt="">
						</a>

					</div>
					<!-- /.col-md-3 col -->

				</div>
				<!-- /.row -->

			</div>
			<!-- /.container -->

		</div>
		<!-- /.item -->
	
		<!-- Start Content Block 2-3 -->
		<section class="content-block content-2-3 bg-deepocean">
			<div class="container">
				<div class="col-sm-7 pull-left">
					<div class="editContent">
						<h2>Sign-up to receive our newsletter</h2>
					</div>
				</div>
				<div class="col-sm-4 pull-right">
					<div class="input-group1">
						<input class="form-control" placeholder="email address"
							type="email">

					</div>
					<!-- /.input-group -->

				</div>
			</div>
			<!-- /.container -->
		</section>
		<!--// END Content Block 2-3 -->
		<*/
      out.write("\r\n");
      out.write("\t\t<!-- Start Content Block 1-6 -->\r\n");
      out.write("\t\t<section id=\"content-1-6\" class=\"content-1-6 content-block\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row text-center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"editContent\">\r\n");
      out.write("\t\t\t\t\t\t<h2>他们都在使用火星在线项目管理</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--end of row-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row client-row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 col-sm-6 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<img alt=\"client\" src=\"images/partner-logos/citibank.png\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 col-sm-6 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<img alt=\"client\" src=\"images/partner-logos/oracle.png\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 col-sm-6 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<img alt=\"client\" src=\"images/partner-logos/toyota.png\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 col-sm-6 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<img alt=\"client\" src=\"images/partner-logos/dell.png\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row client-row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 hidden-sm hidden-xs\">\r\n");
      out.write("\t\t\t\t\t\t\t<img alt=\"client\" src=\"images/partner-logos/GE.png\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 hidden-sm hidden-xs\">\r\n");
      out.write("\t\t\t\t\t\t\t<img alt=\"client\" src=\"images/partner-logos/panasonic.png\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 hidden-sm hidden-xs\">\r\n");
      out.write("\t\t\t\t\t\t\t<img alt=\"client\" src=\"images/partner-logos/intel.png\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3 hidden-sm hidden-xs\">\r\n");
      out.write("\t\t\t\t\t\t\t<img alt=\"client\" src=\"images/partner-logos/sk.png\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /.row -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /.container -->\r\n");
      out.write("\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<!-- // End Content Block 1-6 -->\r\n");
      out.write("\t\t<div class=\"footerWrapper\" id=\"footer1\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div\r\n");
      out.write("\t\t\t\tclass=\"item footer bottom-menu bottom-menu-large bottom-menu-inverse\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-2 navbar-brand\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"\" href=\"#fakelink\"><img alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"images/brush.svg\"></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5 class=\"title\">产品介绍</h5>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"bottom-links\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">火星项目管理是什么</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">为什么选择火星项目管理</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">安全与隐私</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">版本与价格</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">免责声明</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">官方博客</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5 class=\"title\">帮助中心</h5>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"bottom-links\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">热点问题</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">账号问题</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">交流问题</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">管理问题</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">使用说明</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">其他问题</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5 class=\"title\">关于我们</h5>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"bottom-links\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">客服：8008208820</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">邮箱：bxmn4728@Mars.com</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">联系我们</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">在线客服</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">公司简介</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">合作伙伴</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5 class=\"title\">关注我们</h5>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"bottom-links\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">Facebook</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">Twitter</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">Youtube</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">Vimeo</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">Instagram</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /.item -->\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.footerWrapper -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /#page -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Load JS here for greater good =============================-->\r\n");
      out.write("\t<script src=\"js/jquery-1.8.3.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery-ui-1.10.3.custom.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.ui.touch-punch.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap-select.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap-switch.js\"></script>\r\n");
      out.write("\t<script src=\"js/flatui-checkbox.js\"></script>\r\n");
      out.write("\t<script src=\"js/flatui-radio.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.tagsinput.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.placeholder.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.nivo.slider.pack.js\"></script>\r\n");
      out.write("\t<script src=\"js/application.js\"></script>\r\n");
      out.write("\t<script src=\"js/over.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\tif ($('#nivoSlider').size() > 0) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$('#nivoSlider').nivoSlider({\r\n");
      out.write("\t\t\t\t\teffect : 'random',\r\n");
      out.write("\t\t\t\t\tpauseTime : 5000\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t})\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
