/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2016-09-05 08:13:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1473055777548L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"generator\" content=\"Xinglan Wang (bxmn4728@163.com) \">\r\n");
      out.write("<!--pageMeta-->\r\n");
      out.write("\r\n");
      out.write("<!-- Loading Bootstrap -->\r\n");
      out.write("<link href=\"bootstrap/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Loading Flat UI -->\r\n");
      out.write("<link href=\"css/flat-ui.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- load page css -->\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/style.complete.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/myStyle.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("\t\t\t  <script src=\"js/html5shiv.js\"></script>\r\n");
      out.write("\t\t\t  <script src=\"js/respond.min.js\"></script>\r\n");
      out.write("\t\t\t<![endif]-->\r\n");
      out.write("\r\n");
      out.write("<!--headerIncludes-->\r\n");
      out.write("\r\n");
      out.write("<title>火星在线项目管理网</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- SITE HEADER -->\r\n");
      out.write("\t<header id=\"site-header\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<nav class=\"navbar navbar-inverse\" role=\"navigation\">\r\n");
      out.write("\t\t<div class=\"container-fluid navbar-collapse\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"#\"><img src=\"images/hexagon.png \"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 24px\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"login.jsp\" onClick=\"login()\">账户管理</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"login.jsp\" onClick=\"login()\">项目管理</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">解决方案</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<form class=\"navbar-form pull-left\" action=\"#\" role=\"search\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"form-control\" id=\"searchThing\" type=\"search\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Search\"> <span class=\"input-group-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span><img src=\"images/searchIcon.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"height: 21px\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"login.jsp\">登陆</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"page\" class=\"page\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"item header margin-top-0 padding-bottom-0\" id=\"header3\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<header class=\"wrapper image image1\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"bg bg1\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"row banner2\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-8 col-md-offset-2 text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/hexagon.png\" alt=\"logo\" />\r\n");
      out.write("\t\t\t\t\t\t\t<h1>注册</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<form action=\"User?action=add\" method=\"post\" class=\"registed\" class=\"form-horizon\">\r\n");
      out.write("\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Text input-->\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label \" for=\"loginName\">用户名:</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t <input id=\"loginName\"  placeholder=\"用户名\" name=\"loginName\" \r\n");
      out.write("\t\t\t\t\t\ttype=\"text\" /> <sup class=\"surely\">*</sup>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Text input-->\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label\" for=\"input01\">密码:</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\"placeholder=\"密码\" id=\"password\"\r\n");
      out.write("\t\t\t\t\t\tname=\"password\" /> <sup class=\"surely\">*</sup>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Text input-->\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label\" for=\"input01\">重复输入密码:</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" placeholder=\"密码\" class=\"input-xlarge\">\r\n");
      out.write("\t\t\t\t\t\t<sup class=\"surely\">*</sup>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Text input-->\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label\" for=\"input01\">邮箱</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"email\" id=\"email\" name=\"email\" placeholder=\"邮箱\" />\r\n");
      out.write("\t\t\t\t\t<sup class=\"surely\">*</sup>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t          <div class=\"controls\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"注册\" name=\"btnSubmit\" style=\"margin:20px\"/>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<!-- .submit -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /.container -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t<div class=\"footerWrapper\" id=\"footer1\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div\r\n");
      out.write("\t\t\t\tclass=\"item footer bottom-menu bottom-menu-large bottom-menu-inverse\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-2 navbar-brand\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"\" href=\"#fakelink\"><img alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"images/brush.svg\"></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5 class=\"title\">产品介绍</h5>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"bottom-links\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">火星项目管理是什么</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">为什么选择火星项目管理</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">安全与隐私</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">版本与价格</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">免责声明</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">官方博客</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5 class=\"title\">帮助中心</h5>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"bottom-links\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">热点问题</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">账号问题</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">交流问题</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">管理问题</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">使用说明</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">其他问题</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5 class=\"title\">关于我们</h5>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"bottom-links\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">客服：8008208820</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">邮箱：bxmn4728@Mars.com</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">联系我们</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">在线客服</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">公司简介</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">合作伙伴</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5 class=\"title\">关注我们</h5>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"bottom-links\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">Facebook</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">Twitter</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">Youtube</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">Vimeo</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#fakelink\">Instagram</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>");
      out.write("\r\n");
      out.write("\t<!-- HEADER TOP -->\r\n");
      out.write("\t<!-- Load JS here for greater good =============================-->\r\n");
      out.write("\t<script src=\"js/jquery-1.8.3.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery-ui-1.10.3.custom.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.ui.touch-punch.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap-select.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap-switch.js\"></script>\r\n");
      out.write("\t<script src=\"js/flatui-checkbox.js\"></script>\r\n");
      out.write("\t<script src=\"js/flatui-radio.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.tagsinput.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.placeholder.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.nivo.slider.pack.js\"></script>\r\n");
      out.write("\t<script src=\"js/application.js\"></script>\r\n");
      out.write("\t<script src=\"js/over.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\tif ($('#nivoSlider').size() > 0) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$('#nivoSlider').nivoSlider({\r\n");
      out.write("\t\t\t\t\teffect : 'random',\r\n");
      out.write("\t\t\t\t\tpauseTime : 5000\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\tfunction login() {\r\n");
      out.write("\t\t\talert(\"还未登陆，请先登陆\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
